### ISSUE TITLE
Can not detect type

### ISSUE THREAD

**Issue by cuiliang** [zzzprojects/Z.Expressions.Eval#120]
Sample code: https://dotnetfiddle.net/Q2Zh4s

Code  to Execute():
```c#
var code = new[] { "a" };
foreach (var line in code)
{
    var a = new List<string>() { line };
}
```

Error:
```
System.InvalidOperationException: No method 'Add' on type 'System.Collections.Generic.List`1[System.String]' is compatible with the supplied arguments.
   at System.Linq.Expressions.Expression.FindMethod(Type type, String methodName, Type[] typeArgs, Expression[] args, BindingFlags flags)
   at System.Linq.Expressions.Expression.ListInit(NewExpression newExpression, IEnumerable`1 initializers)
   at .(ExpressionScope , SyntaxNode )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , ExpressionScope , String , Boolean , Boolean )
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean , Boolean )
   at Z.Expressions.EvalContext.Execute[TResult](String code)
   at Z.Expressions.EvalContext.Execute(String code)
   at Z.Expressions.Eval.Execute(String code)
   at Program.Main()
```

To solve the problem, need to give direct type to iterator variable:
```c#
var code = new[] { "a" };
foreach (string line in code)  <--- change var to string
{
    var a = new List<string>() { line };
}
```

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

The fix has been merged.

It should be released tomorrow (Wednesday)

Best Regards,

Jon

**Comment by cuiliang** [comment]
Thank you @JonathanMagnan !

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

The v4.0.68 has been released.

Let me know if everything is working in this new version.

Best Regards,

Jon
