### ISSUE TITLE
Cannot define a Func like this?

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/Z.Expressions.Eval#91]
Cannot define a Func like this, but it works in vs.
```
var context = new EvalContext();
context.Execute(@"Func<string, string> Functest = (path) => {
    if (false)
    {
        return path;
    }
    return path;
};");
```

It throws the error like below:

```   
at System.Linq.Expressions.Compiler.LabelInfo.ValidateFinish()
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(LambdaExpression lambda)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(BinaryExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(Expression node, Type type, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Emit(BlockExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvert(UnaryExpression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.Expression`1.Compile()
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , ExpressionScope , String , Boolean , Boolean )
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean , Boolean )
   at Z.Expressions.EvalContext.Execute[TResult](String code)
   at SomeTest.Program.Main(String[] args) in E:\Desktop\Program\C#\SomeTest\Program.cs:line 38
```
```
无法跳至未定义的标签“”。
Cannot jump to undefined label“”。
```

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

Thank you for reporting, my developer will look at what is missing to make it compatible.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.29 has been released.

Could you try it and let us know if that has been fixed correctly?

Best Regards,

Jon

**Comment by cesaryuan** [comment]
Thank you! Works for me.
